### ISSUE TITLE
Update web and printable styling to match PDF bios

### ISSUE THREAD

**Issue by kylegifford** [bitovi/bios#10]
The web output should closely match the PDF version of the bios. This includes:

- [ ] Fixed square image sizes
- [ ] Footer with Bitovi logo and last updated date (pulled from MD file last updated)
- [ ] Fonts
- [ ] Spacing
- [ ] Fixed width page (possibly with some styling to make it look like a document on a page - dropshadow, etc)

Printable should have all of the above, except with the footer fixed at the bottom of each page.

**Comment by kylegifford** [comment]
Redlines: https://www.sketch.com/s/8b68b195-c714-40cb-b509-201b018a62b8

**Comment by itsmikeh** [comment]
Updates initiated in `update-styles` branch with work-in-progress b9956914b07a4b3578a6a0295e927701c59f96d0

**Comment by itsmikeh** [comment]
Resolved by 82dd06d7620b35d96effa6979bfcfa89b7d40f20
